development:
  adapter: postgresql
  encoding: unicode
  database: rails_objects_sample_development
  pool: 5
  username: postgres
  password:
  host: localhost
  encoding: utf8

test:
  adapter: postgresql
  encoding: unicode
  database: rails_objects_sample_test
  pool: 5
  username: postgres
  password:
  min_messages: WARNING
  host: localhost
  encoding: utf8